from enum import Enum


class ResnetSourceEnvKeys(Enum):
    CIVILIAN_PLANES_DIR = "RESNET34_CIVILIAN_PLANES_DIR"
    EMPTY_PLANE_DIR = "RESNET34_EMPTY_PLANE_DIR"
    MILITARY_PLANES_DIR = "RESNET34_MILITARY_PLANES_DIR"


class TargetEnvKeys(Enum):
    RESNET34_DATA_TARGET_DIR = "RESNET34_DATA_TARGET_DIR"
    RESNET34_LABEL_TARGET_DIR = "RESNET34_LABEL_TARGET_DIR"
    YOLO_DATA_TARGET_CONFIG_PATH = "YOLO_DATA_TARGET_CONFIG_PATH"


class ModelEnvKeys(Enum):
    RESNET34_WEIGHTS_PATH = "RESNET34_WEIGHTS_PATH"
    PRETRAINED_YOLO_WEIGHTS_PATH = "PRETRAINED_YOLO_WEIGHTS_PATH"
    YOLO_WEIGHTS_PATH = "YOLO_WEIGHTS_PATH"


class MetricsEnvKeys(Enum):
    RESULT_METRICS_PATH = "RESULT_METRICS_PATH"
    CONFUSION_MATRIX_PATH = "CONFUSION_MATRIX_PATH"
    F1_CURVE_PATH = "F1_CURVE_PATH"
    PRECISION_CURVE_PATH = "PRECISION_CURVE_PATH"
    RECALL_CURVE_PATH = "RECALL_CURVE_PATH"


class TestEnvKeys(Enum):
    YOLO_TEST_SAMPLE1 = "YOLO_TEST_SAMPLE1"
    YOLO_TEST_SAMPLE2 = "YOLO_TEST_SAMPLE2"
    MODEL_PIPELINE_SAMPLE1 = "MODEL_PIPELINE_SAMPLE1"
    MODEL_PIPELINE_SAMPLE2 = "MODEL_PIPELINE_SAMPLE2"
    MODEL_PIPELINE_SAMPLE3 = "MODEL_PIPELINE_SAMPLE3"
    MODEL_PIPELINE_SAMPLE4 = "MODEL_PIPELINE_SAMPLE4"
    MODEL_PIPELINE_SAMPLE5 = "MODEL_PIPELINE_SAMPLE5"
    MODEL_PIPELINE_SAMPLE6 = "MODEL_PIPELINE_SAMPLE6"