from enum import Enum


class ResnetSourceEnvKeys(Enum):
    CIVILIAN_PLANES_DIR = "RESNET34_CIVILIAN_PLANES_DIR"
    EMPTY_PLANE_DIR = "RESNET34_EMPTY_PLANE_DIR"
    MILITARY_PLANES_DIR = "RESNET34_MILITARY_PLANES_DIR"


class TargetEnvKeys(Enum):
    RESNET34_DATA_TARGET_DIR = "RESNET34_DATA_TARGET_DIR"
    RESNET34_LABEL_TARGET_DIR = "RESNET34_LABEL_TARGET_DIR"


class ModelEnvKeys(Enum):
    RESNET34_WEIGHTS_PATH = "RESNET34_WEIGHTS_PATH"
